stages:
  - trigger-jenkins
  - build
  - push

trigger-jenkins:
  stage: trigger-jenkins
  script:
    - CRUMB=$(curl -u "$JENKINS_USER:$JENKINS_PASSWORD" "$JENKINS_URL/crumbIssuer/api/xml" | grep -oPm1 "(?<=<crumb>)[^<]+")
    - curl -H "Jenkins-Crumb:$CRUMB" -X POST "$JENKINS_URL/job/codejudge/build?token=$JENKINS_JOB_TOKEN"
  only:
    - master

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_USERNAME/fan_onlinejudge:$CI_COMMIT_REF_SLUG .
  only:
    - master

push_image:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push $DOCKER_USERNAME/fan_onlinejudge:$CI_COMMIT_REF_SLUG
  only:
    - master
